export const pages = ['Home', 'Send', 'Company', 'Admin'];

export const settings = ['Credits', 'Records', 'Account', 'Logout'];

export const branches = [
    {
        id: 0,
        name: 'Restaruace u Čápa',
        street: 'Sídliště',
        houseNo: '4',
        city: 'Toužim',
        postalCode: 36401,
        capacity: 200,
        occupancy: 17.2,
        tax: '0%',
        open: 1,
        owner: 'Jakub Verner',
        coords: '50°3\'34.192"N,12°59\'4.462"E',
        opens: 7,
        closes: 14,
        sunday: 1,
        warehouse: 0
    },
    {
        id: 1,
        name: 'Nákupní středisko Petry Smutné',
        street: 'Vepřová',
        houseNo: '32',
        city: 'Huzová',
        postalCode: 79351,
        capacity: 2000,
        occupancy: 26.4,
        tax: '0%',
        open: 0,
        owner: 'Petra Smutná',
        coords: '49°49\'17.041"N,17°17\'53.068"E',
        opens: 6,
        closes: 21,
        sunday: 0,
        warehouse: 0
    },
    {
        id: 2,
        name: 'Hudební středisko HLAS',
        street: 'Kostelní',
        houseNo: '56',
        city: 'Stanovice',
        postalCode: 36432,
        capacity: 5000,
        occupancy: 2.7,
        tax: '5%',
        open: 1,
        owner: 'Karel Rachot',
        coords: '50°9\'57.066"N,12°52\'24.165"E',
        opens: 9,
        closes: 17,
        sunday: 1,
        warehouse: 0
    },
    {
        id: 3,
        name: 'Kavárna U Stromu',
        street: 'Javorová',
        houseNo: '12',
        city: 'Brno',
        postalCode: 60200,
        capacity: 85,
        occupancy: 65.3,
        tax: '10%',
        open: 1,
        owner: 'Lucie Marečková',
        coords: '49°11\'43.2"N,16°36\'35.4"E',
        opens: 8,
        closes: 20,
        sunday: 1,
        warehouse: 0
    },
    {
        id: 4,
        name: 'Sportovní hala Třinec',
        street: 'Sportovní',
        houseNo: '99',
        city: 'Třinec',
        postalCode: 73961,
        capacity: 1500,
        occupancy: 30.5,
        tax: '21%',
        open: 0,
        owner: 'Vladimír Dvořák',
        coords: '49°40\'48.6"N,18°40\'59.2"E',
        opens: 6,
        closes: 22,
        sunday: 1,
        warehouse: 0
    },
    {
        id: 5,
        name: 'Knihkupectví Modrá Luna',
        street: 'Hlavní',
        houseNo: '8',
        city: 'Zlín',
        postalCode: 76001,
        capacity: 120,
        occupancy: 55.0,
        tax: '0%',
        open: 1,
        owner: 'Jana Bílá',
        coords: '49°13\'21.9"N,17°39\'59.7"E',
        opens: 9,
        closes: 18,
        sunday: 0,
        warehouse: 0
    },
    {
        id: 6,
        name: 'Květinářství U Anděla',
        street: 'Nádražní',
        houseNo: '27',
        city: 'Plzeň',
        postalCode: 30100,
        capacity: 60,
        occupancy: 40.8,
        tax: '15%',
        open: 1,
        owner: 'Tereza Fišerová',
        coords: '49°44\'34.5"N,13°22\'56.7"E',
        opens: 8,
        closes: 19,
        sunday: 1,
        warehouse: 0
    },
    {
        id: 7,
        name: 'Fitness centrum Raptor',
        street: 'Zdravotní',
        houseNo: '42',
        city: 'Olomouc',
        postalCode: 77900,
        capacity: 300,
        occupancy: 72.3,
        tax: '21%',
        open: 1,
        owner: 'Milan Krátký',
        coords: '49°35\'47.1"N,17°15\'59.4"E',
        opens: 5,
        closes: 23,
        sunday: 1,
        warehouse: 0
    },
    {
        id: 8,
        name: 'Dětské centrum Sluníčko',
        street: 'Školní',
        houseNo: '10',
        city: 'Třebíč',
        postalCode: 67401,
        capacity: 90,
        occupancy: 88.9,
        tax: '0%',
        open: 0,
        owner: 'Martina Pokorná',
        coords: '49°12\'2.3"N,15°52\'59.1"E',
        opens: 7,
        closes: 17,
        sunday: 0,
        warehouse: 0
    },
    {
        id: 9,
        name: 'Galerie Moderního Umění',
        street: 'Galerijní',
        houseNo: '2',
        city: 'Hradec Králové',
        postalCode: 50003,
        capacity: 250,
        occupancy: 11.4,
        tax: '5%',
        open: 0,
        owner: 'Šárka Novotná',
        coords: '50°12\'33.2"N,15°50\'42.3"E',
        opens: 10,
        closes: 18,
        sunday: 1,
        warehouse: 0
    },
    {
        id: 10,
        name: 'Depo Alpha',
        street: 'Logistická',
        houseNo: '1',
        city: 'Praha',
        postalCode: 10100,
        capacity: 8000,
        occupancy: 52.1,
        tax: '0%',
        open: 1,
        owner: 0,
        coords: '50°3\'20.0"N,14°28\'10.0"E',
        opens: 6,
        closes: 20,
        sunday: 0,
        warehouse: 1
    },
    {
        id: 11,
        name: 'Depo Beta',
        street: 'Skladová',
        houseNo: '15',
        city: 'Brno',
        postalCode: 60200,
        capacity: 6000,
        occupancy: 70.4,
        tax: '0%',
        open: 1,
        owner: 0,
        coords: '49°12\'30.0"N,16°36\'0.0"E',
        opens: 5,
        closes: 22,
        sunday: 1,
        warehouse: 1
    },
    {
        id: 12,
        name: 'Depo Gamma',
        street: 'Technologická',
        houseNo: '5',
        city: 'Ostrava',
        postalCode: 70030,
        capacity: 7500,
        occupancy: 33.3,
        tax: '0%',
        open: 0,
        owner: 0,
        coords: '49°49\'0.0"N,18°15\'0.0"E',
        opens: 7,
        closes: 18,
        sunday: 0,
        warehouse: 1
    },
    {
        id: 13,
        name: 'Depo Delta',
        street: 'Dopravní',
        houseNo: '12',
        city: 'Plzeň',
        postalCode: 30100,
        capacity: 9000,
        occupancy: 28.7,
        tax: '0%',
        open: 1,
        owner: 0,
        coords: '49°45\'0.0"N,13°22\'0.0"E',
        opens: 6,
        closes: 21,
        sunday: 1,
        warehouse: 1
    },
    {
        id: 14,
        name: 'Depo Omega',
        street: 'Areálová',
        houseNo: '8',
        city: 'Ústí nad Labem',
        postalCode: 40001,
        capacity: 8500,
        occupancy: 60.5,
        tax: '0%',
        open: 1,
        owner: 0,
        coords: '50°39\'0.0"N,14°2\'0.0"E',
        opens: 5,
        closes: 19,
        sunday: 0,
        warehouse: 1
    }
];